GET http://localhost:3000/users

###

GET http://localhost:3000/users?limit=2&offset=2&order=oldest

###

GET http://localhost:3000/users/70e1e61d-f2ae-4d7d-bf8f-d65eafdb6a45

###

GET http://localhost:3000/users/6c3a18b0-11c5-4d97-9019-9ebe3c4d1317/saved-products

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "yjkim@example.com", 
  "firstName": "유진",
  "lastName": "김",
  "address": "충청북도 청주시 북문로 210번길 5",
  "userPreference": {
    "receiveEmail": false
  }
}

###

PATCH http://localhost:3000/users/a8ae7e71-4a23-4df0-9dba-a904cf0abc9f
Content-Type: application/json

{
  "email": "yjkim2@example.com",
  "userPreference": {
    "receiveEmail": true
  }
}

###

DELETE http://localhost:3000/users/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e


###

GET http://localhost:3000/users/6c3a18b0-11c5-4d97-9019-9ebe3c4d1317/orders